apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- nodejsapp-route.yaml
- nodejsapp.yaml
- nodejsapp-config.yaml
images:
- name: edisaac/nodejsapp
  newTag: develop-a3b6698
